In [1]:
# Based on this article for attempted projection into the future:
# https://medium.com/@rupesh1684/stock-market-prediction-using-machine-learning-model-svm-e4aaca529886

# Import Python Librariesimport numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
import pandas as pd
import numpy as np 

df1 = pd.read_csv("archive/Stocks/aapl.us.txt")
df1 = df1.iloc[:,:-1]

In [2]:
display(df1.tail())

Date    Open    High     Low   Close    Volume
8359  2017-11-06  171.75  174.36  171.10  173.63  34901241
8360  2017-11-07  173.29  174.51  173.29  174.18  24424877
8361  2017-11-08  174.03  175.61  173.71  175.61  24451166
8362  2017-11-09  174.48  175.46  172.52  175.25  29533086
8363  2017-11-10  175.11  175.38  174.27  174.67  25130494

In [3]:
df = df1[['Close']]
df[['Close']].tail()

Close
8359  173.63
8360  174.18
8361  175.61
8362  175.25
8363  174.67

In [4]:
#Create one more column Prediction shifted 5 days up. 
df['Prediction'] = df[['Close']].shift(-5)
#print data set
display(df)

C:\Users\0king\AppData\Local\Temp\ipykernel_14224\1024679487.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Prediction'] = df[['Close']].shift(-5)


Close  Prediction
0       0.42388     0.44566
1       0.42134     0.45718
2       0.42902     0.44052
3       0.41618     0.43157
4       0.43927     0.43286
...         ...         ...
8359  173.63000         NaN
8360  174.18000         NaN
8361  175.61000         NaN
8362  175.25000         NaN
8363  174.67000         NaN

[8364 rows x 2 columns]

In [5]:
#Create a data set X and convert it into numpy array , which will be having actual values
X = np.array(df.drop(['Prediction'],axis=1))
#Remove the last 5 rows
X = X[:-5]
display(X)

array([[  0.42388],
       [  0.42134],
       [  0.42902],
       ...,
       [166.29   ],
       [167.51   ],
       [171.88   ]])

In [6]:
# Create a dataset y which will be having Predicted values and convert into numpy array
y = np.array(df['Prediction'])
# Remove Last 5 rows
y = y[:-5]
display(y)

array([  0.44566,   0.45718,   0.44052, ..., 175.61   , 175.25   ,
       174.67   ])

In [7]:
# Split the data into train and test with 90 & 10 % respectively
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [8]:
# https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html
# SVM Model
svr = SVR(kernel='rbf', C=1e3, gamma=0.1)
# Train the model 
svr.fit(x_train, y_train)

SVR(C=1000.0, gamma=0.1)

In [9]:
# The best possible score is 1.0
svm_confidence = svr.score(x_test, y_test)
print('svm confidence: ', svm_confidence)

svm confidence:  0.9987963239494283


In [10]:
forecast = np.array(df.drop(['Prediction'],axis=1))[-5:]
display(forecast)

array([[173.63],
       [174.18],
       [175.61],
       [175.25],
       [174.67]])

In [11]:
# support vector model predictions for the next 5 days
svm_prediction = svr.predict(forecast)
display(svm_prediction)

array([146.74484721, 134.34897359, 106.40462129, 112.30778405,
       123.59890779])